### ISSUE TITLE
add_features fails

### ISSUE THREAD

**Issue by ehsankakaei91** [neurosynth/neurosynth#97] opened 2020-10-26 15:56 UTC
It seems they have removed **DataFrame.to_dense ** from pandas. So I cannot add features to my data set.

"  Removed Series.to_dense, DataFrame.to_dense (GH26684)"

**Comment by adelavega** [comment] 2020-10-26 18:21
neurosynth is officialy deprecated, so the only possible solution will be to downgrade pandas 

see: https://github.com/neurosynth/neurosynth/issues/96

**Comment by adelavega** [comment] 2020-10-26 18:25
I updated requirements.txt to recommend 0.x series pandas (i.e. not 1.x). Closing this as a dupe of #96

**Closed by adelavega** 2020-10-26 18:25 UTC
