### ISSUE TITLE
Viewer Bug

### ISSUE THREAD

**Issue by ljchang** [neurosynth/neurosynth#49] opened 2015-02-26 00:42 UTC
I've been having some problems with the viewer since the last update.  Specifically, for the decoding results, selecting a neurosynth term will (slowly) add a new layer, but then only the axial view works.   Removing the offending layer ends up removing the entire layer table.   Unfortunately, this doesn't happen every single time and I haven't been able to figure out the circumstances, but it has happened multiple times on different computers

**Comment by tyarkoni** [comment] 2015-02-27 01:26
This should go on the [neurosynth-web](https://github.com/neurosynth/neurosynth-web) repo, so I'm closing it here and opening it there. I can't reproduce it myself after trying a few images, so probably won't look into it further until someone figures out what precipitates it...

**Closed by tyarkoni** 2015-02-27 01:26 UTC
