### ISSUE TITLE
Difference between code and website in number of studies around coordinates

### ISSUE THREAD

**Issue by tsalo** [neurosynth/neurosynth#63] opened 2015-12-18 21:04 UTC
Running **get_studies** for a peak with a 6mm radius gives me roughly the same number of studies as a **Locations** search with 12mm radius on the website. I haven't looked into the code, so I don't know which one is right.
  
Results:  

| Seed        | web r=6 | web r=12 | code r=6 (02/15 data) |
| :---------- | :------ | :------- | :-------------------- |
| 0 0 0       | 343     | 1424     | 1386                  |
| 20 20 20    | 95      | 601      | 545                   |
| 46 -40 46   | 488     | 2010     | 1757                  |
| -46 -40 46  | 518     | 2157     | 1830                  |
| 0 32 20     | 273     | 1364     | 1181                  |
| 0 -48 30    | 334     | 1459     | 1208                  |
| -28 -18 -18 | 299     | 1345     | 1212                  |
| 28 -18 -18  | 291     | 1250     | 1095                  |

**Comment by tyarkoni** [comment] 2015-12-18 21:13
Thanks for catching this. I didn't write the search code for the web app, but based on the above table, my guess is that either the web app is dividing the radius by 2 or the imageutils code is multiplying it by 2. The counts otherwise look close enough to be explained by the difference in DB versions. Will look into it.

**Comment by tyarkoni** [comment] 2015-12-18 21:48
Okay, I think I've figured out the problem. The issue is that the Mappable images are stored internally post-smoothing. I.e., every peak is already represented as a sphere of radius r (where r is specified when the Dataset is initialized). Unfortunately, the search algorithm proceeds by itself growing spheres around the passed coordinates and then checking whether each Mappable in the Dataset has non-zero values overlapping with the generated mask. Which means that, in practice, when you ask for a radius of 6, you're actually getting some larger value (roughly the radius you ask for plus the radius of the Dataset).

The fix for this would ideally be to avoid using images entirely, and do a simple Euclidian filtering on the raw x/y/z coordinates, which is how the website does it. The trouble is that the raw activations aren't always available, because the Mappables are deleted by default when the Dataset is pickled in order to save space.

I think a reasonable way forward is to stop deleting the entire mappable objects, and only drop the associated MNI-space volumes (as those are already re-represented and saved in the ImageTable anyway). It would probably make sense to keep metadata around anyway. Should have a patch soon.

**Comment by tyarkoni** [comment] 2015-12-24 23:21
Changed this in adc05d39. The search results now perfectly match the website results you quoted, but let me know if you run into any further issues.

Incidentally, to fix this, I completely did away with the notion of a "Mappable", and instead switched to representing all activations in an internal pandas DataFrame (in the .activations property) that's basically just a copy of the original data file. This means I dropped all the add_mappable/delete_mappable functionality (I apologize for wasting your time on it!). But it's for a good cause--I think the new approach makes much more sense!

**Closed by tyarkoni** 2015-12-24 23:21 UTC
Labels: bug
